server:
  port: 8082

spring:
  config:
    activate:
      on-profile: local
  application:
    name: consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
