apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: producer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: kafka-config
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  namespace: producer-consumer-kafka-demo
  name: producer-service
  labels:
    app: producer
spec:
  selector:
    app: producer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
